services:

  mariadb:
    container_name: MariaDB
    build: MariaDB/.
    ports:
      - "3306:3306"
    command: '--socket=/run/mysqld/mysqld.sock --datadir=/var/lib/mysql'
    networks:
      - inception_net
    volumes:
      - mdb:/var/lib/mysql
    env_file: .env
    restart: on-failure

  wordpress:
    container_name: WordPress
    build: WordPress/.
    ports:
      - "9000:9000"
    networks:
      - inception_net
    volumes:
      - wp:/var/www/html
    restart: on-failure
    depends_on:
      - mariadb
    env_file: .env

  nginx:
    container_name: NGINX
    build: NGINX/.
    ports:
      - "443:443"
    networks:
      - inception_net
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - wp:/var/www/html
    restart: on-failure
    
  
  adminer:
    container_name: Adminer
    build: Adminer/.
    ports:
      - "80:80"
    networks:
      - inception_net
    depends_on:
      - mariadb
    restart: on-failure

networks:
  inception_net:
    driver: bridge

volumes:
  mdb:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /tmp
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /tmp
