services:
  adminer:
    container_name: Adminer
    build: Adminer/.
    ports:
      - "80:80"
    networks:
      - inception_net
    restart: on-failure

  mariadb:
    container_name: MariaDB
    build: MariaDB/.
    networks:
      - inception_net
    volumes:
      - mdb:/var/lib/mysql
    env_file: .env
    restart: on-failure

networks:
  inception_net:
    driver: bridge

volumes:
  mdb:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /tmp
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /tmp
