#!/bin/sh

service mysql start

# mysql root exec
SQL_CMD="mysql -u${MYSQL_ROOT_USER} -p${MYSQL_ROOT_PASSWORD} -e"

$SQL_CMD "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};"
$SQL_CMD "CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';"
$SQL_CMD "GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';"
$SQL_CMD "ALTER USER '${MYSQL_ROOT_USER}'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';"
$SQL_CMD "FLUSH PRIVILEGES;"
mysqladmin -u${MYSQL_ROOT_USER} -p${MYSQL_ROOT_PASSWORD} shutdown

exec "$@"
